version: '3.8'

services:
  service1:
    build: ./service1
    container_name: service1
    volumes:
      - ./logs/service1:/var/log/service1
    ports:
      - "8001:8001"

  service2:
    build: ./service2
    container_name: service2
    volumes:
      - ./logs/service2:/var/log/service2
    ports:
      - "8002:8002"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ./logs/service1:/var/log/service1
      - ./logs/service2:/var/log/service2
    command: -config.file=/etc/promtail/config.yml

  loki:
    image: grafana/loki:latest
    container_name: loki
    # user: "1000:1000"
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0"
    ports:
      - "3000:3000"
    depends_on:
      - loki

networks:
  loki-network:

volumes:
  loki_data:
