server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: service1-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: service1
          __path__: /var/log/service1/*.log

  - job_name: service2-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: service2
          __path__: /var/log/service2/*.log
